### PR TITLE
Added optimizations

### LINKED ISSUE #25: Add optimizations (as a setting)
For longer programs, it can be tedious to run through code even at the fastest setting. Additionally, stepping through 10 plus's to debug something you actually care about is tedious.  

Possible optimizations:
- lump together +'s, -'s, <'s, >'s
- `[-]` sets the cell as zero
- `[->+<]` adds one cells value to another

This probably shouldn't be enabled by default. There could be a checkbox or have the fastest speed on the slider use it.

If you would be open to a PR, i would be happy to do it.

### PR DESCRIPTION
**Pull request by TheThirdOne**
Lumping instructions and `[-]` optimizations were added.

Only runs optimizations if the speed is set the 30.

Fixes #25

### CODE REVIEW

**Comment by TheThirdOne** [comment]
It would probably be better to have a checkbox for optimizations.

**Comment by TheThirdOne** [comment]
Any feedback on this?

**Comment by fatiherikli** [comment]
Hey sorry I just noticed it.

**Comment by fatiherikli** [comment]
It's merged now. Looks good, thanks :+1:

**Comment by fatiherikli** [comment]
this.interpreter.next($("#optimize").is(':checked'));

Did you add checkbox for this check? I can not see

**Comment by TheThirdOne** [comment]
I have it on my local version. I must have forgotten to add/push it.

**Comment by fatiherikli** [comment]
Haha okay :') I'm waiting

**Comment by TheThirdOne** [comment]
Should I make a second PR or is there a better way of throwing on one extra commit?

**Comment by fatiherikli** [comment]
I guess you should create a new pull request.

**Comment by fatiherikli** [comment]
Btw you can add yourself to contributors section in README.

**Pull request merged**
