### PR TITLE
Add the checkbox

### PR DESCRIPTION
**Pull request by TheThirdOne**
A quickfix for #26

### CODE REVIEW

**Comment by TheThirdOne** [comment]
Yo @fatiherikli

**Comment by fatiherikli** [comment]
Thanks :+1: 

It will be deployed in a few hours.

**Comment by TheThirdOne** [comment]
I'm not seeing it on [http://fatiherikli.github.io/brainfuck-visualizer/](http://fatiherikli.github.io/brainfuck-visualizer/).

**Comment by rdebath** [comment]
That URL points at the `gh-pages` branch. If you want to see `master` immediately you can download it and run it locally or use:  https://rawgithub.com/fatiherikli/brainfuck-visualizer/master/index.html

Of course `gh-pages` is getting a bit "stale" and should probably be updated.

**Pull request merged**
