### PR TITLE
Add share support from URL

### PR DESCRIPTION
**Pull request by f**
Adds base64 snapshot of BF code to the URL. Basically adds support to share your BF code with your friends.

### CODE REVIEW

**Comment by rdebath** [comment]
I just tried [this](https://rawgit.com/f/brainfuck-visualizer/c34d2293620192ebdae6233c4d63384436ba81b5/index.html#K1s+Pls+XSs8Wy08XTxdCg==) and it *autoruns* the BF. Firstly this doesn't seem consistent to me, but more importantly the buttons aren't switched correctly and the init doesn't seem to have run correctly for me. This in Chrome.

**Comment by fatiherikli** [comment]
What do you think @f? Should we disable auto-run functionality?

**Comment by fatiherikli** [comment]
I'm removing auto-run functionality for now.

**Comment by fatiherikli** [comment]
It's deployed now. Thank you @f :+1:

**Pull request merged**
